# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.


version: 2
updates:
  - package-ecosystem: "bundler"   # See documentation for possible values
    directories:
      - "/updater"   # Location of package manifests
      - "/"
    schedule:
      interval: "weekly"
      day: "sunday"
      time: "16:00"
    groups:
      sorbet:
        patterns:
          - "*-sorbet"
          - "sorbet-*"
          - "sorbet"
          - "tapioca"
      aws-sdk:
        patterns:
          - "aws-sdk-*"
      prod-dependencies:
        dependency-type: "production"
        update-types:
          - "minor"
          - "patch"
      dev-dependencies:
        dependency-type: "development"
        update-types:
          - "minor"
          - "patch"

  # Watch the per-ecosystem native helpers
  - package-ecosystem: "composer"
    directories:
      - "/composer/helpers/v1"
      - "/composer/helpers/v2"
    schedule:
      interval: "weekly"
      day: "sunday"
      time: "16:00"
    groups:
      prod-dependencies:
        dependency-type: "production"
        update-types:
          - "minor"
          - "patch"
      dev-dependencies:
        dependency-type: "development"
        update-types:
          - "minor"
          - "patch"
  - package-ecosystem: "devcontainers"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "sunday"
      time: "16:00"
  - package-ecosystem: "docker"
    directories:
      - "/"
      - "/go_modules"
      - "/cargo"
    schedule:
      interval: "weekly"
      day: "sunday"
      time: "16:00"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "sunday"
      time: "16:00"
    groups:
      all-actions:
        patterns: [ "*" ]
  - package-ecosystem: "gomod"
    directory: "/go_modules/helpers"
    schedule:
      interval: "weekly"
      day: "sunday"
      time: "16:00"
  - package-ecosystem: "mix"
    directory: "/hex/helpers"
    schedule:
      interval: "weekly"
      day: "sunday"
      time: "16:00"
  - package-ecosystem: "npm"
    directory: "/npm_and_yarn/helpers"
    schedule:
      interval: "weekly"
      day: "sunday"
      time: "16:00"
    groups:
      npm-dependencies:
        patterns:
          - "@npmcli/arborist"
          - "nock"
          - "npm"
          - "semver"
        exclude-patterns:
          - "detect-indent"  # temp excluded due to https://github.com/dependabot/dependabot-core/pull/5683#issuecomment-1243468605
      yarn-dependencies:
        patterns:
          - "@dependabot/yarn-lib"
      pnpm-dependencies:
        patterns:
          - "@pnpm/lockfile-file"
          - "@pnpm/dependency-path"
      dev-dependencies:
        dependency-type: "development"
        update-types:
          - "minor"
          - "patch"
    ignore:
      - dependency-name: "npm"
        update-types: [ "version-update:semver-major" ]
  - package-ecosystem: "pip"
    directory: "/python/helpers"
    schedule:
      interval: "weekly"
      day: "sunday"
      time: "16:00"
    groups:
      common:
        patterns:
          - pip
          - cython
          - flake8
      poetry:
        patterns:
          - poetry
          - hashin
      pip-tools:
        patterns:
          - pip-tools
      pipenv:
        patterns:
          - pipfile
          - pipenv
  - package-ecosystem: "pub"
    directory: "/pub/helpers"
    schedule:
      interval: "weekly"
      day: "sunday"
      time: "16:00"

# Basic `dependabot.yml` file with
# minimum configuration for two package managers

version: 2
updates:
  # Enable version updates for npm
  - package-ecosystem: "npm"
    # Look for `package.json` and `lock` files in the `root` directory
    directory: "/"
    # Check the npm registry for updates every day (weekdays)
    schedule:
      interval: "daily"

  # Enable version updates for Docker
  - package-ecosystem: "docker"
    # Look for a `Dockerfile` in the `root` directory
    directory: "/"
    # Check for updates once a week
    schedule:
      interval: "weekly"
      
     
      
